# --------------------------------------------------------------------
# Permissions
#
# ALL PLAYERS HAVE PERMISSION TO USE '/sumo join' & '/sumo leave'
#
# sumoevent.command.help > Allows player to use /sumo help
# sumoevent.command.ver > Allows player to use /sumo ver
# sumoevent.command.start > Allows player to use /sumo start
# sumoevent.command.stop > Allows player to use /sumo stop
# sumoevent.command.reload > Allows player to use /sumo reload
# sumoevent.command.startmatch > Allows player to use /sumo startmatch
#
# --------------------------------------------------------------------


# Sumo platform worldguard region name (must be lowercase).
region-name: sumoevent

# -----------------------------
# Format for Locations:
# worldname,x,y,z,direction
# -----------------------------

# Spawn point of the players on the sumo platform.
loc1: events,44,69,-1,west
loc2: events,34,69,-1,east

# Spawn coordinates of the sumo spectator platform
sumo-spawn: events,23,67,-1,east

# ---------------------
# Reward Configuration
# ---------------------
rewards:
  # Rewards given to the final winner
  final-winner-rewards:
    - "eco give %winner% 1000000"
    - "give %winner% iron_block 10"
  # Rewards given to the final second place winner
  final-second-place-winner:
    - "eco give %winner% 1000"
    - "give %winner% iron_block 3"
  # Rewards given to the winner of each round
  round-winner:
    - "give %winner% gold_block 1"

# ---------------------
# Lang configuration
# ---------------------

# Message Prefix
message-prefix: "&d[SumoEvent] &e"
# Message to be displayed when an invalid number of arguments are passed in.
invalid-argument-amount-message: "Invalid number of arguments."
# Message to be displayed when an invalid argument is passed in.
invalid-argument-message: "Unknown argument."
# Broadcast Message to be displayed when a sumo event has been started
sumo-event-started-message: "Sumo event has started."
# Broadcast Message to be displayed when the sumo event has ended.
sumo-event-ended-message: "Sumo event has ended."
# Message to be displayed when an admin attempts starting a sumo event that is already running.
sumo-event-already-running: "Sumo event is already running."
# Message to be displayed when an admin attempts to stop a sumo event that is not running.
sumo-event-not-running: "There is no active sumo event."
# Message to be displayed to the player when they have joined the sumo event.
player-joined-sumo-event: "You have joined the sumo event."
# Message to be displayed to the player when they attempt to join the event when they are already in the queue.
player-already-in-queue: "You are already in the queue."
# Message to be displayed to the player when they leave the sumo queue.
player-left-queue: "You have been removed from the sumo event."
# Message to be displayed to the player when they attempt to leave a queue they are not in.
player-not-in-queue: "You are not in the queue."
# Broadcast message when there are not enough players in the queue to start the event.
not-enough-players-message: "Not enough players to start a match."
# Broadcast message when a winner has defeated the loser on the sumo platform
player-has-been-defeated-message: "%winner% has defeated %loser% on the sumo platform!"
# Broadcast message to announce the event winner.
player-won-sumo-event: "%winner% has won the sumo event!"
# Message to be displayed to the player when they do not have permission.
no-permission-message: "&cYou do not have permission to execute this command."
