# --------------------------------------------------------------------
# Permissions
#
# ALL PLAYERS HAVE PERMISSION TO USE '/sumo join' & '/sumo leave'
#
# sumoevent.command.help > Allows player to use /sumo help
# sumoevent.command.version > Allows player to use /sumo ver
# sumoevent.command.start > Allows player to use /sumo start (Admin command)
# sumoevent.command.stop > Allows player to use /sumo stop (Admin command)
# sumoevent.command.reload > Allows player to use /sumo reload (Admin command)
# sumoevent.command.forcestart > Allows player to use /sumo forcestart (Admin command)
# sumoevent.command.giveflare > Allows player to give other players a sumo event starter
#
# --------------------------------------------------------------------


# Sumo platform worldguard region name.
region-name: sumoevent

# -----------------------------
# Format for Locations:
# worldname,x,y,z,direction
# -----------------------------

# Spawn point of the players on the sumo platform.
loc1: events,44,69,-1,west
loc2: events,34,69,-1,east

# Spawn coordinates of the sumo spectator platform
sumo-spawn: events,23,67,-1,east

# Time in seconds to wait for players to join before starting the actual game.
require-force-start: false # if this is true it will require you to force start the match using /sumo forcestart
match-start-delay: 180 # This value should be in seconds (must be a multiple of the countdown interval)

# This is the interval that will broadcast a message to the players
sumo-event-countdown-interval: 60

# ---------------------
# Reward Configuration
# ---------------------
rewards:
  # Rewards given to the final winner
  final-winner-rewards:
    - "eco give %winner% 1000000"
    - "give %winner% iron_block 10"

  # Rewards given to the final second place winner
  final-second-place-winner:
    - "eco give %winner% 1000"
    - "give %winner% iron_block 3"

  # Rewards given to the winner of each round
  round-winner:
    - "give %winner% gold_block 1"

sumo-summoner:
  material: RED_MUSHROOM
  display-name: "&c&lSumo Event Starter"
  glow: true
  lore:
    - '&7Unleash the thrilling'
    - '&7excitement of Sumo wrestling!'
    - ''
    - '&eRight-click to start the event.'

  # Commands executed on voucher redemption.
  commands:
    - 'give %player% diamond 1'


# ---------------------
# Lang configuration
# ---------------------

# Message Prefix
message-prefix: "&d[SumoEvent] &e"
# Broadcast message to be displayed every x interval configurable above (sumo-event-countdown-interval)
event-status-broadcast-message: "The sumo event is starting in %time_left% minutes, there are currently %player_count% players in the queue."
# Message to be displayed when an invalid number of arguments are passed in.
invalid-argument-amount-message: "Invalid number of arguments."
# Message to be displayed when an invalid argument is passed in.
invalid-argument-message: "Unknown argument."
# Broadcast Message to be displayed when a sumo event has been started
sumo-event-started-message: "Sumo event has started."
# Broadcast Message to be displayed when the sumo event has ended.
sumo-event-ended-message: "Sumo event has ended."
# Message to be displayed when an admin attempts starting a sumo event that is already running.
sumo-event-already-running: "Sumo event is already running."
# Message to be displayed when an admin attempts to stop a sumo event that is not running.
sumo-event-not-running: "There is no active sumo event."
# Message to be displayed to the player when they have joined the sumo event.
player-joined-sumo-event: "You have joined the sumo event."
# Message to be displayed to the player when they attempt to join the event when they are already in the queue.
player-already-in-queue: "You are already in the queue."
# Message to be displayed to the player when they leave the sumo queue.
player-left-queue: "You have been removed from the sumo event."
# Message to be displayed to the player when they attempt to leave a queue they are not in.
player-not-in-queue: "You are not in the queue."
# Broadcast message when there are not enough players in the queue to start the event.
not-enough-players-message: "Not enough players to start a match."
# Broadcast message when a winner has defeated the loser on the sumo platform
player-has-been-defeated-message: "%winner% has defeated %loser% on the sumo platform!"
# Broadcast message to announce the event winner.
player-won-sumo-event: "%winner% has won the sumo event!"
# Message to remind the player that force start is required
force-start-required-reminder-message: "Force start required using /sumo forcestart (you can update this in the config)"
# Message to be displayed to the player when they do not have permission.
no-permission-message: "&cYou do not have permission to execute this command."
